language: node_js

node_js:
    - 8
    - node
env:
  - NODE_ENV=test
  global:
    - CC_TEST_REPORTER_ID=6f8c00044ea93ac24eb7f426a34ac9a90d0ef5a31044445d8d44f4c5ff7d2d60
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
    - npm test
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm install nyc
  - npm install coveralls
  - npm run coverage
  - npm run coveralls
   